global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: fanoutservice
    static_configs:
      - targets: ['fanoutservice:5004']
  - job_name: searchservice
    static_configs:
      - targets: ['searchservice:5000']
  - job_name: usergraphservice
    static_configs:
      - targets: ['usergraphservice:5000']