{
 "title": "authservice",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "gc latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "http latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "p99 eventoop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "auth_service_nodejs_eventloop_lag_p99_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p90 eventloop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "auth_service_nodejs_eventloop_lag_p90_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(auth_service_http_transaction_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}