{
 "title": "fanoutservice",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "kafka latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Total Kafka Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(fanoutservice_kafka_transactions_total{job=\"fanoutservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"fanoutservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"fanoutservice\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}