{
 "title": "readservice",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"readservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "healthCheck Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "gc latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"readservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(go_gc_duration_seconds_count{job=\"readservice\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    { "expression": "$A/$B", "type": "math" }
   ]
  }
 ]
}